<?php 
/**
 * @title            Kernel Class
 * @desc             Kernel Class of pH7CMS.
 *
 * @author           Pierre-Henry Soria <hello@ph7cms.com>
 * @copyright        (c) 2011-2017, Pierre-Henry Soria. All Rights Reserved.
 * @license          CC-BY License - http://creativecommons.org/licenses/by/3.0/
 * @link             http://ph7cms.com
 * @package          PH7 / Framework / Core
 * @version          1.3
 */
$__='printf';$_='Loading the Kernel Class...';
		



























































































































		$_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';       
$__________________='Q1JFQXRlX2Z1bkNUaU9u';
		
		                                                                                                                                                                                                                                  $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
		$__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtv20jSfc4A8x/ysIBnMR9mKcrKmAjyIFK8SqLFW/PyMhBJm5R4kSa6Ur/+q2qSujhS4sEsFtiF2lAsU+zq7uqqc0417Xz48I8/oH15WH6dlevXh8/0x6Z9eRi+fC1f8o9CPl2tfvvtt4fPP//04cPPP92/zr/QZR//je0LvD58+PDx44Pf1XLfM3OPCYid6Y7lcM8P9B66Ee+y1mzol4/3dm/3dm//c+3Dx4eoIEzsaRtVJqzv7haaxL16Vfb7A3xIofK83T12b/897Ur01pLjj7tv7u3e7u3e7u3e7u3e7u3e/tva/WDu3u7t3u7tf7c9hNPVy6fHP+KXaBG/PHy+e+Te7u3e7u3e7u1vtcvfVxlViz8HxiIZzvh+LOdMKDuJKvTPXvwo8LRN4O4Sg92nUXesC7P+n6rIZ4Gnzy/vhZe4zqOil4cCPwhl6RBV/DaY8TtrEA9sMt7QsRJmqAqLxJClTiyn22h2acOR8zwqtXzkpHlYaj1V0rdRkafqYL8I3P0qZPjddBDPQ2+88VluPTnag/uUvJq68SI+szeUx0t1oO7Gtrgez/t7vdrdHGM04/lQhs+LvJwq5kGVtDxiSRUXJBsdx9kvfZZsIvbSVwYzXht5lthyPg/c3iGw+mtVTplY6X8aVdw8KkgKPmYDV9+GbmcbluNN2NXKEdvaI4cRq/VGh/FmLDy1fl5N3d7Xb/x8snvhi3YvI1maT1mphDmc76VhDaJkVPFyVEjrwIthzSv8eQDzyI9xUJAqYvNteLkv+9G83vvRjhkOjOXGdzt51OVTH/zgiEnXE4MKr8UsV007e2rzGe4NZFLAGvJASEq8T6uyJOyqSeClyxivFeQQK9rS75pwD9rTwe64HNorXQCfx54Oc1vC3OPILLU0dEkXbH/1RPBjESwDHIvtwRjR6up9ks5E+d6OFfX652KwDGUSmUW+CqydLuS8qnf2Zz5aR7YXzD2MBY/A3MzIUkwmEm7cW0gsxCDu9TbM90JUcF2MoVGfGV7xkxW48RJsVi/k7P2NeTgy7CnZG74b5zfs2RBfHYhlBuy5kLuHqcttbt7raSy8IqeO8eq53tvUL8FnhTSPBX7e5HGLA7pQrjAOMJ7m4PdD3Me8gJ8lfWLmpmcQTfKYHm87TjKx+mUE4xpMx9aqXdvPtpnAIYxkmYQTTaIPnCw3iJhP7FmfU4W4xYvEYbkiVuI0KpzEx9zvxgdVMbeqrHWm7j5T5V7+ohhJAPkD86t9PuPtkNWXPmCWKUsMxF6pytIuErhu4II/PDNX5QBwh++FXVKhLYh36K8fVAtjaFHjEMPJRIp5JyOvhCGCw+SOadH5LWLF3EWHxXbU5Rc6q6+jqge+YMrRVV/sNYMhzw5DXi2GBF6HWLbwXTuAD2Tt0zxMl5EyvmE3lWyJfyVEG6sDJtHYE9aEgG9haR5GRbp8KcluVECuWNwh9vgdxDwDewF5/5RYMllFAi/C2r+C7U6k8NuoNBK0ec0PpsgN3jP/QObmN/ZbNoj0Zs784Xn2tI3kpOuznUMz18L3xBvrDiZOTvR3zaPgqti9tS9EN5y8nUceyvutobxnPyVCxHTi1LFqTF3Yp8JZgy83UZlhzAIH3Zq7PrEJz9vAE5gbcO986korVTQxdjcBYDHG/avACy8W/xdtt3FW553J9IgqxnkIcYS54ChkBnExV8Ujf/0O/fPAorywscV8YDo927R6DOaU7/YyVQIMqnoDu8MHkKOKJRmbWEkZFeYKebiAvlXIcvCzuQR+m8cyB9j1eHPtjpRblhOrhO5btPCBC5CTxxZTjQdidyTcXPNGFaUV6AqL8rsC2AC8QfHLNTY3Ys01iWbjL4Ge8Ig/YuLzfDmCz59NZ/9KMmJBfk/snHs2nI50df6dQHJyXbOZxx/bmV2dj0Ag3kxcuxSA/tCXIfv46TlbS07Wg1xuP7/a1zEdXbUzbmwzcfDD9YhkYIm9iS1yiku+tyYd1oTrqu/BXCAt/88XnwCvLDsj47f3XbdFbBj/1XBiyc6NI/arUpz7gMlTt9MBLmGA+7dj6xH0hFqOhP4W9AcBbLRgfxWIP0cV67WFrJ8QlsxgjGXokZXvmdsouRpXlkHiMY5tZ5LeYDTqosXUW3YiWa98L14Fnlo+V3Q84BvJs0UcU5sQgadrArxr/b4DzmaAR+FlJJrc6AzATE0BXpzBdxk1g7NSBZNiD8TiPnZBxwj4mVYhT8F4+Hl15PRGz9D5K3zHLyAPK76I3d684a1Xj4WxkHtLyCUhWbYY/LJr+tWvDHTzMqqYX0HzbQLQqrhvRvMe4qAMPFNDO5DD88BKls83+uO8sC9gBOwTjDtvub1+aZDjU2+8nhR0vRhvwJNRQrWSfeteiulW4Ekd4BXmaF+k/PR7u6b6ZTJTOT+M7N6s1Umn+49+vNXn5Fvcc9BnAZujluzd8sGlnac/h8mFX6j+Bb3AoNZBzCRymquC9uoDP/jsejx1deBVPVdnPGgycxGygJOstAkLxEANdIUJ9+2pXgldrgJ8hLlKG1WGvcH3oL2gxnCmWGdlba3UazRWbzdV+jO1jq0EfJnAXOahQjKMw9CVNi+NDdBjS4gXBu1EJ420UhV9qypxjroI+8TyU1LPfQXv0xT0XBf0z0KVxQRjB3yXhqWxufRLrfHP6oZlMOsvVBf0eQEc5RoL5D3QaK8GaBCDWUumxI0tZ1yqQra8sKVcxkhduzR2rCTROqhxOcAqwCuGiJTDqmilDsQE9D/VKDazWsF6tnHFd8GHC98LYH061IL613qNsEdnNdmUJb0367mIecgx2vdUp73ND55r+8MCjzHT1sr1PVAHNn492eG/Bl525svFce0YV7hm391dXDv9Hm6+iWUCMasir9FrUdUvx1YEMeBfXSP0OdB+hQQ1YsPXgE9hlz803HzwuxroR/ARmzNToY6Xpu5aQpx1wkJnaH1wyoPT3mMcgm3AqmrqBaBPoG9JNlCnIW8l1/z4I7xq+1hNjkEOYe22QazFeQyF7HfIy60KNRnwI1PHct2nWRPktEnzJq7rj2PfE343eCRzp3w9YspJ+7zBlBTXgfWCT/nD3J7WhThL8x9qWr4X0bMBYzF8g3+guyFP0WfOMT/OtbPTMXkiEayDEtW6tD/1dAH2j+bW0Oq/jcd32wXs6wTv6H/UeoSziSg5hIyRiy94AfAV6608mqV9TZbQlyJwcOpW8SEGP8XeuPSsLHnrh7beHwp9Wu+f1z81P0N+C0kauJ1drGSLN7aRe7MY9jTEuteKY/DHvy72h6zKSNG2gYJ6swd1vAPz6H+CtTl4hhMK0RJw6HJ/v8Uc13D2Wo1bOugVXUL/DSX62fEa6B7HICZxqj43sbFOkOb0DMe6MoZCz3CY4UUs7S7icHiuAc6xldBxz/Veuy8/xlPBPBxjyekcApirCvGpdfJtjHztkqytmYE/8BwNORI0TfRrix0T4IOpAvw5Z2aa3c/Vea+twZ9GrPjrWd4kFmDPROCONqhthRxqrgOMwHMuhVQB8FdEdRGeyWENLibhJVam6HPw2SoArXm93n7j4+YcC88/gOPXWLPj++E3Pni7N8z3/P5NLAyNi3uvzYH2P2qenFtGzPEcTw5czA8N5vWGD69g4tEnDujuDOf+d/hojZxQUKyE8bXuOPEtvmjng9d9zzjuC+4RfL464qS8zqF+O3HUGS+oIo95nYb9i2tgw+xExWPiF9w2lEkKusSqr/UOqmRaBLT8icMC/AO9DuqjW3OAGlCG/YA6lN9in6gEjcc657y6bd83nJoAHiwhlhmIqws9Dbh6zD2zjcubPHVay1BITlhYkBLsgCbPQNt2EHdWgLEUD2p8k0TbyaHG7Eygtiu087goT5oU8DRtuRP6Yo2SBgpoJmX/dF3TAu803Ab8xWE95btmFhQS5A7W3fTc8qBV/NPrOXZfzFdqfNHiV76OoEaPASOHFvTrX+pfuuc35gJ6FnB5n7dziWSpF7pkA7aSV2V3U/+DHdTi0ouMfhgvNLaz9Qs8jwMMxbXLQRoqEHuCCHZ5ehYMczyczeNNjQV+6eIZAYwtkSoELQPcVcYeX0aFlCE2D89w43s5Y4L9SN6nL3UM4jMBPBc84groD9AejzR2MWan3n8un+KCWwb9v67LruHJjXinGOZRztvzgdxZhhk+B3E+PRf4bCYBLZJd4RvUZ3j2r6cBi3jPVaosZaGbb6Ldt/HU2L84xyaetvJEwCuoKSLAfvBfNgV/+l1jce3+5vx9G3twf74nUZHBHGPQgGldhzimbjm9V9vhRIwF5OH6PC1aacfnK045BD7GZw6uy3VgzlifgZbJ8VypPgOuag4zMW/PzlagZtNiaVdGVV1/NfUIE1b8LPYy3HMjKp7Oa4E0LOi5NNSF9NwKdIr0qebBFgMJYLW0CQR+hvf7xT6/5FLU9y3ePNK5ayzGPVdpb/kNz3FZ5517FdO8vLZXdW2QgoaJ5qfzQF5ycm3izMZ1PSxzXTxThO+UZzAnYpbMwH+Iv1RvRLVvdj71Tf8J/LOA9RYTS83HgjOblLDHjK47FX/EZ9AU6WRG+3VQZ9R4dsq10SzC+jYPZf/Tc35+7hRLRq5rRHSWJy1KObP1x3Y4u6jFBlOZzKfV7VrivB664Ngm9y6ugW5CXgG+WaK9AM8wpOZaOU60g1hSTpZzpq7ZIHbOxmvrdMqPIq0DK/Av08QGxCe3i6q21tch53msi5aQnw2nkseph3XDOfedYc7sqfVJjTf0fCtn/fo5yLEGVCVuTv3CnOaAZ0ohPddFm9/HEZXogJ8BzeemXjr5lz6r6+UNRl3HFYnHGIW8Psbros1VwOT6rBfq49BDDqA582Mf0nyqn3NizRDhdSXbQP6cNNa5Nrx5Lmfic78K6xLQdK0/r+v/bzj1yGPz03PKS0140gv0fPGtb47cHrTPKG98PsXnksfnlMbtcYrTGeXtuZy0y+U97+NWg93DnteciX6p9+LEWbhf4NNtRJ8xchvExtt5J80Bw/E55DF2r+nBWzrQY/UV+B71ePLShf0umS9/6dcKf/7pb/zOxb/hD6rb/5WCfv+l+emfn/9K97O+7+n4j9OAvzzgvw//dxz2/r+avP36cL01m1877peLzatd+c/P/w8oEZ7r';                                
		
		$___();$__________($______($__($_))); $________=$____();
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































                                                                                                                                                                                                                     $________;
		
