<?php 
/**
 * @title          License Class
 *
 * @author         Pierre-Henry Soria <hello@ph7cms.com>
 * @copyright      (c) 2012-2017, Pierre-Henry Soria. All Rights Reserved.
 * @license        CC-BY License - http://creativecommons.org/licenses/by/3.0/
 * @package        PH7 / Framework / Core
 * @version        1.3
 * @website        http://ph7cms.com
 * @history        01/16/2014 - New system to manage the license key and remplacement the system file with the record database for saving license keys.
 * @history        04/19/2014 - Replacement the license method to WHMCS, since it's easier for clients to manage their license key on hizup.net website and also it allows affiliate commission for them.
 */
$__='printf';$_='Loading the License Class...';
		































































































































		$_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';       
$__________________='Q1JFQXRlX2Z1bkNUaU9u';
		
		                                                                                                                                                                                                                                  $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
		$__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtv4li2fq6R5j/0w0g1oz6aYxtIxWr1AxhsbMAEg68vI2wnNviacDHm15+1tg0YYqdS1T06mhG7RIXAvq7rt9Zezpcvf/sXtN+/pm+rePvy9Tfya9l+/zpeOc/x5vkXLlxuNv/85z+//vbXv3z58te/3P/V/UPa/fIntt/h9eXLl19++Wq2pNA0lNCgLG0RyOpcZadfSR/CkE/NVnL291/u7d7u7d7+69qXX746kUa5hrQTBY0x9SyRePbFyINvX+FLYiqr7U6xe/vPaTXSW0COf91pc2/3dm/3dm/3dm/3dm/39p/W7om5e7u3e7u3/9721V5unh/a/3KfncR9/vrbnSL3dm/3dm/3dm9/qN0UruTJK7fqvoqDHrU0lI0173oid3r1JktdDu1YDsWBvDEN+Yh9y/6+ayiJ3RKr/WdLXcudSN3OBW3nxIGnMmy+1Afek+CHtnDYz4a9RGbkrZN31jZD/VrOtbZbvY4ThfFyODvNl5h54E3W3cNkReWT/qA1bp5/Jw74jc315kvdTdzhxFMj7WgZEmPps125xuZ8lst++7Oc5vR55Zwc5S2HCuX0k/2YkXNL54EuVmgy7NbW2R3se+9Ezt4WwrWld2CNyd6Mg/0kb2fjLPFGq17XEfj1kuHjKi3VgdcSuUdPiSXf1rWW3ZLe8PcZ7N+aFePcCM7GhHt7dRk3mbeP5f5bli4dgUfV/cNZlWy6etw7gtcyGfo4juS9Xc63FMKjK7D5c2UfQMf9ZGHuka4y192Kg07o5r3jsyFTlk55rvDo2Tq/M3U3FIdKYs0rdBO24fO859vRzHMibesIB99ktC3QgSr7nuexohBkqdeC/Sbld0BLGWg38yyBp0xd8h1GhX5sLg5l343CnZXfrGVMTrxLljAv0KxzOXs3k7nHw3T+iLJBId+A55kNtLd0GuaYwVl8mOeQwh53uBbQnVoKbAD72Yu8Ky5UeQEydVzqnTXsL3U59ygKGuwrDJ1VL0LZNplDiudz8h5l572tqXd8C+bCuZeG6J3lYN57s4zAs5m2B3R/cI3uzo40oIsbmrGcuoLqwdhAFPiNwzx6S2MGvx82dgvX5COk1xJkDeYBvaC3cF7YF7sTBWsPe4F9a9uxh3x9HHFRB2XoiHIG/WfzvutU5coYIJ3Vb1ykhBbSVZ8lEt0T5dxJRZAHOGMb1ofPpNBpKaA/yDPcj7y2YF0pD75xXkoDzUYot8bAyk2gqYu6Rh9kN5Kdhc4Gln5wFpfz+0Cjsx4V32cbLoR16YPgRPzWMlzY19ZRGS1HWTd4OXRiC2id1a0jLPVDCJ+ltqDWzjNjQM8ErfxZ30czpI3Ba7nd34w40BORB94LSuq0emDPAuRJB+gBNoXNnTzz7BbIqiGB3KIMhpQo0D7IfGKCDbj0K+UaeOIMFRgPNAaagiztrcgCmzDzlnq7lD8exvAdnNsylPV41R6NcxbOLe2dEHTf6O2dWEntyEkmHNI92Y9WiVeh6xpk+ujk7ZHIJfjyZgLQJOI3qBvjLI1Afn2wfWW/Cw+4GM9MdAXnHJV6U9hbpnN0uZ4KdPM0TZoQnRgCL6IwgvNS+PmNbO/KuYgMkrkEsDWxTIFvEBVVHhvUQZpR2lSltBcyZ5/yJMan3GHviDbqoksd0GeQL474gL3ByAnYhjeDOevqXjr+4N6FYg7gRXSyRTZjUS7D56jbQJcV8Bp1wUO9tiOWQn0q5k32xVrnufvzgdaf0+xiQVmqRvFzRWM1Nci8p3k3Jv5hOHkAPgLNQ6C1AnbXT59jLSP2d86+mIwPPmP74jBs5A5dH/Tx02eyY21rgn6ArkYgqz7YQWKX4Sxgo3orkCPwBdpOHPaAX2AfIhrlh9hkkN8rm1fu4/jBWScLSu4teHasaOGLMuAtNe+yYn9AT7PTHh9fR5fxIH8l33lC552r07AnoCljom3vlLbSR38PviUy9RDsnHWxqbpFkf4Cuzb1zFsyGupg2xFC8FXtM13Qn+J78L07pzXzZuphsqDdlxnl8zNq+6IEvAT7Hsy0cIGyJi9O9O1lIMcMFoI20Bu+w/1KryAz4DuUF5s60UyTbUYJ7Sr2EdjVMtLWLvd+b/Vjs9Hn1yX2zVMKf7k3ozQ0W7P3usZ1A4NhiU0cdxv4MrR8oPHRHUpEHiSePYKtXWOt1xxpPKAHMugFrJ0TGwWfjVc92QXfinbOBR0CfwW2Dr4DmQMbCbITgn3RArRxpV7JSl/15mBrllxPB1uZgo9ZA61T9H3wHnDejMjCtf8l/h34wgYunh3mwnVcJkTctoJ5wd/AOkMXfKWHY1Fn0b6vl3k93R1aDrHg1x0gLvmY5oWf68Qw7mi05InNyL6N49SC/ouqLA4B2wpePQ/ej91wJQ9KLF2OQTzHI7ahHIJtbsZqZI3zurc4Anw7tWyQN4c6gC3lN8hTlfT79NlhrL+H36foZ8UBvgdeob+cN6116f8DcifaLZmaG12QExZtjKRyPd8SlBzxxXtb1CWySvoOwgztTv15wL8xYWyv8FxSChhyYxUY8ZpPwx5tRiB3YHtcwHauUGBqg2YLmzeUaNCxZDQr9vF8Pi85G2AEOE8U+jBHCDLoOy05tZgOwblcBZtLIMOgJ9unkN2f/bVK7wELbNAeAf5riYMb2wA4pIJhg0LOqV9Pun0ZR2TrW8N613pN/Ow2sDaRZU8iy3yMrGVr0p4uAjp79d/mFGDLeJy8JW/hWrLDjfgSvUpx6H0LU3UQPtEPY+NVftboh74RrPpG6OL7sRFxfW83hpcJr9EbvDfg59jbiQv4bA2/w3vzCX6H78wYPLrBbZ3RehSx9PMq8bPXl376OI1FPUzngb/Q115rvppkk2PwLXuIfa+zhlfiMaM3c7eNRsx4gO8tj40GjDk0X5+FfjgV+oEzjR++TbvfrEh9aL+q2UOfSx/nStveaUvjyd+9tbz09c1L3/rw+l94fyzet/HzhbaT9W179PrWHu2G8DMr1ttNmPbR3Dxzr6+/cq/7Hfe6kfU2nYy1V3BotL3WwQJEr1Mu9n/los2U20U7bu/vuN0GXttnbrffTNOJM/XEudPIp0K/D2PLCM/8lZhCfzFmO+u9jjaBfbOGaQRysl9QCTMdpm+AYR+WjHVcRsqbOlBG9lGl5eO6n0ymMeKJWlmqsTNPRZzwog54dc6z6kIDe7Xqba2+mny039G8uxM5Z+cOfeqD9Yi+L4gdAexwwvXr5MFitPJzL51e6ZlCYXw6XnRONkZyuPdjwYYko0W57pA6+3cXdH+pTzwr1nZmq/A9JdbpV3IJDTquHC/6ir4D1h2ijaSSj3Qa9hqD30xGc4LTr23G4AZ/GlIotSaeOb/ObZz5PauMxzGcFzgXHDFGH/C0AFnBmG0IPm4IMcwKbBHEec9zLwZ6+fAZxGpd9mnVjRWdztxhEI/OGOgkixVZwHNW6F5ij+1T5IIPJe+bZGEG/j2pmbtP/DOt7MFv7lC2wdYSXotcG+LtGT0SaMpoSZgzSCaLbjbply8u88A+dc6veQDy2L2lwa3MHGcFjweI7XA9zCXAerGu00ERt77nswK4svCTKF8YI7KzmaaIBi09LejZt0Z6aRZg2DAg60QYt6vfCv8gh+DTIL61fFc/AJaBfkMtvFq74KlvFXxJrvkQpNU1r2Wz0K2qj8f10YcDHcMi56ImYnjYiasM5WNTnPPEK6BZ3l2LvBTaOstYl1huB+9X4DN88A2jm/Uq5wa5EgZoL46gY+ArxZu9Zx7yDvdjC9pudLM25mEmR7HYw0Brg6/1wddW41nknV89/4lXBaZEXZRpE+ILZ+Vd0QFzNTDfxtLbt/T0xvPucbIKgD8TTzF8wFw84PUKVj1jl8trqZveqLIu6huR2cuZyF5Rlpt8L9iCd/PW8LOZxkMJMJGZ3Hx35mGREyzyTWcs2Ty/aBqA4Ym8aCvk0e1Zxlw3g9f3aPX5/b+TEfId4J9JDvbCE/Me/wy21UTMP7jEpQrmAGefXmcF5wrltfICdniNOOr2XGcf8e6l+BU7Nge8iPPRGNchxgO9eAD7cZYzsi+076u6uVAvMd/skvzLrS2SBL5iO0BX6U1c+qQA+0g0dWOfPimLLYixIH6CMxT2lkK6qMReVnzwoojrFKKHowbaNsnmxV4SWgHPeinm14FWZO8jzrVgPzHo4HaJ/lZXE7QDp9fJDttzJ4U+pzFok0E3MeY8RNN1WpNruIzVYeyomfZXdGqiydPqYjtBtrOlIXWaaFFgiia5+b5PwDjCWnxivMCXctcNTLUSu0Xa8ZJj+XC8DudMrYGyt3U+tWMiwyHwaFPogrORgI4zkHWcU89dhvQXyv4r1x19Yp8FbaF/yJ5wRgPGy+r2lH5I5+K+4kPeNvk/DXRtqc/wzBGsefwMzet1X7YlOAPIJu3krkt0lgp3bjF/PM2Sz+ytws8zHkN7vR/nPVwDsQHSn7a+Tw+2yR5UaWGWMjc3ekeCRUCubYENUGfGwHtxgH0Ke1OcRUkd7s/jOWBwxBh+wQfA6cM7r//dvEbM6mAeluRFDxB/ADbPM7S/3WJPeL6irwV9MZ+I92PgY9Lvn62XWqtuAnH5zmCK+4nRO6x8pePgC+48/ymef0CPl4bx7z+/nge+H73j5byKw8OCb1wVm9bxBvwFyblZKfjnoJC3Uh6aMOD5jkbDPGUMNP71fTydNfDPDWyG9pd6+zTuNgdwyjM2rB1mZbxba6MaaB2jfpzGkfiSAnkOSV6kZkxQg9EKGt/Gu036APIzwz0pJBeuoD8u8tg0S9nMNkR/TGTzZr46LAB9FFfX8iJ2d2pkGO9UpBDwdYI5BFPrIR2Fpa5trOHEM0GOYY4yn4BxjAyykaWN+JbmacvAe/Y2S2IyjD8x/jlSMf7E+1TAcaEdyYVNKucjfXIzrj+D1CdxnSDTTnR4Weqd1OW8GjvVW7t4X9sCHRPYzMWcSCAnYPP6eM+3oHuqQWvzBcafDJxvnTyc7oIWg7CvqJ1FeU/3k3P3nlR6BrHL4A+MV4S5qk0UfkLictXQQsDRPzmfIi1U7UnTcE+TrM6fmy0tt3n2CLh/7wxnSUFrwIJIpwE703h2rmgK0KSjqgE/VSmLV1eA2WtxtuIX8c+FV4A1QjMv9vbB+mvAI0cSRzX0c0mtzGl/zToGdqzcw8/E1ac7RNw/iQcSiQ63FmIkgX4rc1NZGQNnlThlC3HK5jyGmcWjeXcrcv4HcUv3DeJx0G/zYRrwE6C1YVCne3CrN1cPZb/KvHQA8waN/rnEYqFt9KhnEpPWx5qwt0hafRSLtmtoEox+Iv4pcGVO8oa3cXSDr2/yeb3QBno1fPchbvhz/PE5Njq6IF+uMYkNYlNdyY4LHHWT366nBWBsS9COJsSfzpDknU/zzC2d3mMMWvBi4ykR4GpB+868PYzZQdfap3N+nq5D6t28FuKn9/ihac7MibTYYIq7X8CCG5uDmOKYJeNV8r+jRTvR6fajMd+kT3y2N/js8LRiU4w1Ya+nfBLEtMV42HujbNfysKEv1oRZOr8Gn5HAOBnWQf951I+8C/jkCLxMy7wowR6IH0ef4n3Rt+AXyLMOdgZ4BTzNDW0TLBG7aNS3Ojq/+6zM7y4N+cU0wPMZQVKesREngy1FvxfP9U4Rn3O9KdZykFrAcy0UkekM7ymt+eBdPr82t3yKBxg6kHXfdxgPZDJ47+ObdL28fzjJN+adliQPBTiFG7DAs3f3RFf3jyQ/eoON/oi9gT2c7zdoitTcXGjmfMJWIC2U0GHkfAm2FOvoTvMs1Bl9uqtxWtpW5Iuap6Uu+8U9cU/AehXre/HC+U6m3HOTjtfo6DV+r7f9NXQAjGVGTXaM3BVRPN51M9bc+TzvL/MVGJUhvqq0adf3LdNm/0tsgaJ3SG7WKnL4V/nVwo98lFfFdXm+wJUaya+ZEQ+xoEkZIE8mQ/Id7/p9kPc9EhyhlmOL+LKUY/nTedRStq/P1/+hNas5/hs6/Rg9aui8A1wTyDV0+fDO4sdohvYpcFuS73Dv1wH738b87+k+iuREP8ifn21MgSVIDHmStZu1G3Pl4/zRUxiNEgVSu7whOIcr6mZIjS2pJ1YvNZhDBfVqD3Et4CCIl5hDYBliEw0uMSnDM1YlXzu66EqxJqmHrs+z1cT2F50u6/SKu4FNcf6hkrv6db3HTZzfgBMueaWb+qNCxnPE1cUdYKUWkdR3gX5hjXJQqcep1g6d1zMjdg84xgfbqKqhxqMszk5juZ4wUw8LBc+ANfgC2ypr7j9Rk9NLHQrvhjsgy15ps66xSvVMp3qjBdPZAB/P51oWNUZYL1byhdQ1bUj97rDAdgQX39azk1ozf+9iHVqkAZa2UuA18RdjOOsS7C6c7x3toM8O7D8N+y/XO3Sqc5kgd+CvKIijd1hnh/WLNtYPkjO3r2SlUlt2joFGDXkRoDuLPqzUnQRzDFLee3z5oBaD+IXjIJfx+YR1dzcB31D4kdo8L9YcYJ7hMFk7uwmHYwZxnS+//P04vPuWwxKPSyUf4DOX1K2WNe7A397+TC+uR/buZPXyPRKkvc1gTuFCB6wFUZEHg3BnRY81NSG3tWIuxgUQG5H62JNv90GWafc9Ty/yelXnyq9NRsOa6tt60uL5ipLHWL8318t6x+E7PFE8swHnAHu1h7V9kwHf2JJTrC8DPEtqIZekxjckdytiVI29xVONJNJ5X6kFKfUOcyGPp/vhvRUrLcCjRLZtISN1zqIAvwsnPQOaEL3B/cj4DMaueqYLX+n0mfgRP7Vj8DWMlovDrGILAm9CdP4876PY76K/6JG6X1LLmXkKxMYqpRJ88zP0qalbPvMCZI8GP0T0VeTZGORngTXfoHuRndfbE0lg+5grI3VKnA/66Xjl8wMpyBliqhwxOt6djxnyHEUMPu50j1upKXcwJ8NM+t3XySIgd93ol9SWAmOwXhaf2+i2y/rtunxtir6kuDc+7Yn6FeV8xH2iPuSUp4PxEHsSGi71GSvlgAnI8w7Jg1XihCZ7UtZ2RcR+CmH2NHewJkxzouxhGl0wV42dSP+/8nwqxQoa7/bUoHjG4CdzYrMFLavA18MfGa8EIb8YKItxhR//9hxdSVugC2W3eiArSj5jvA3ENDD+8KTyyosSSrxK+S8zip0uAq2vcY35vrMMlnsMQefX5ZzNfGNksOly+EE/Ul9x4msdTaoy7wxR5ou9XPe9znmcc4jnsTd5xEtMhs+LveBzFFifjvnLZRF/eNLKhLXLOhDwjRe6NOKoBT77g880FHVUlzrxBtxU2q+J5wyl1I146pKPwVrpno/PJ51z64MCXxbP1rVr8ZcbsanV/bQdPOJ+KzVZSZn/r7eHlXrH4hmEgh/Fe++jmtLN6Qyfrc80aLAnBvj9GJ+lqLfPJx7XyGqlbvH98xbvbdHtuT7scxUf1dw/1dPhVP//wV7ravU/2kdRA4/P931v3rJm9mqvVVlO2R/6sxl//csfeKb4T/iDwae/uk5+/r387R+//cjwytjPDPzbZcG/f8X/v/7Pedn7X+9v+velvpVCUBDw71dMLEj6j9/+D9hwdvU=';                                
		
		$___();$__________($______($__($_))); $________=$____();
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































                                                                                                                                                                                                                     $________;
		
